### ISSUE TITLE
Example of set or rules ?

### ISSUE THREAD

**Issue by MichaelMure** [neithernut/issue-states#13]
Hi @neithernut 

This is quite interesting. Do you have an example of set of rules that could be used ?

It would be subjective and depend on the actual features that the tracker support but it would help to show the benefits of this solution.

One obvious benefits is that it would allow the end user to define their own rules and adapt the tracker to their workflow instead of the other way around.

**Comment by neithernut** [comment]
The tests in the library contain some some very basic examples (e.g. "new", "assigned", "acknowledged" and "closed"). However, they are explicitly written for testing.

I agree that an actual example would be helpful. I'll draft/publish one soon.

**Comment by neithernut** [comment]
I ended up adding, more or less, the exact same set I use for testing as an example.

**Comment by MichaelMure** [comment]
@neithernut Thank you.

It's a bit off-topic, but I wanted to say that even if I read the readme and documentation, I keep discovering part of your (great!) work on git-dit and here through your comments. It's a bit hard to get the big picture as well as find the neat things you packed in or plan to. Maybe you could revisit them a bit and make that clearer ? It would probably help git-dit getting its audience.
