### ISSUE TITLE
Condition format

### ISSUE THREAD

**Issue by neithernut** [neithernut/issue-states#15]
I think a format for conditions should be specified. Of course, the library should also gain support for such a format (how exactly the interface will look like is another interesting question which I do not want to discuss here).

The original idea was to have the user declare a suitable format for conditions. The rationale behind it was that specifying a format may be too restrictive. However, specifying a format would clearly improve (potential) interoperability of tools and software making use of issue states. It would also avoid a situation where a user or admin would have to "learn" a new condition format for every new tool.

[git-dit](https://github.com/neithernut/git-dit) already has a format for conditions. It allows checking for:
 * presence of a piece of metadata (just the name of the metadata)
 * presence + exact match of value (`<name>=<value>`)
 * presence + contains substring (`<name>~<value>`)
 * negations of any of the above (`!<condition>`)

The supported datatypes so far are strings and lists of strings. A longish-term plan included adding more operators (e.g. `<` and `>` for numerical or partially ordered values).

One option would be to just take this format, add a bunch of operators, and include it in issue-states. But I'm not sure. Maybe the format could be improved.

@MichaelMure, given that [git-bug](https://github.com/MichaelMure/git-bug) is a potential user, do you have any ideas or preferences?

**Comment by MichaelMure** [comment]
@neithernut in all honesty, I'm way too far on the design of git-bug to have a meaningful input here.
